### ISSUE TITLE
Support Matrix not listed

### ISSUE THREAD

**Issue by tom31415** [jerrybendy/url-search-params-polyfill#14]
What browsers and versions will this work with?

**Comment by jerrybendy** [comment]
I'm sorry I didn't test browsers supporting yet. And I don't know how to build a supporting matrix, could you tell me how ?

**Comment by tom31415** [comment]
Looks like you updated the information with the caniuse website, nice job.

**Comment by stephan-v** [comment]
That matrix has nothing to do with the actual browser support of this polyfill. It is about fetch. This still don't a proper matrix with the browsers that are supported with this polyfill.
