### ISSUE TITLE
Error in IE 11 - Expected identifier

### ISSUE THREAD

**Issue by Soenhay** [jerrybendy/url-search-params-polyfill#16]
Javascript error:
Expected identifier

Internet Explorer Version 11.0.9600.18738

If I delete the following and everything after then the error goes away:

    /**
     * Deletes the given search parameter, and its associated value,
     * from the list of all search parameters.
     *
     * @param {string} name
     */
    prototype.delete = function(name) {
        delete this [__URLSearchParams__] [name];
    };

**Comment by Soenhay** [comment]
This link appears to be related:

https://arstechnica.com/civis/viewtopic.php?t=185317

**Comment by Soenhay** [comment]
Changing 
prototype.delete
to
prototype['delete']

And changing
this.delete (keys[i]);
to
this['delete'](keys[i]);

Removes the error but further testing is needed to see if it is an actual fix.

**Comment by jerrybendy** [comment]
I just tested on my IE 11.1480.14393.0, and everything worked well. The link you gave me is about IE and extending HTML elements.

Although `delete` is a key word in javascript, but using `delete` as an object's property is allowed.

Such as:

```js
// They are allowed 
var Obj = function() {}
Obj.delete = function() {}
Obj.prototype.delete = function() {}
```

**Comment by Herst** [comment]
According to <http://kangax.github.io/compat-table/es5/#test-Reserved_words_as_property_names> IE11 ought to support reserved keywords as properties quite well. This is not the case for IE8, are you sure you weren't in the IE8 rendering mode @Soenhay?

**Comment by Herst** [comment]
According to <http://kangax.github.io/compat-table/es5/#test-Object/array_literal_extensions_Reserved_words_as_property_names> IE11 ought to support reserved keywords as properties quite well. This is not the case for IE8, are you sure you weren't in the IE8 rendering mode @Soenhay?

**Comment by Soenhay** [comment]
"Display Intranet Sites in Compatibiliy View" was checked but I am not currently able to reproduce the issue  so checking or unchecking it does not appear to change anything.

Changing it to "this['delete']" was not really any use either since calling delete would not work.

It appears to be working for me now though.

**Comment by Soenhay** [comment]
It is actually still not working.

**Comment by Soenhay** [comment]
In relation to this link: https://docs.microsoft.com/en-us/internet-explorer/ie11-deploy-guide/fix-compat-issues-with-doc-modes-and-enterprise-mode-site-list

The default document mode on my page in IE11 is 5. If I change it to 8,9 or 10 in the emulation tab then the "Expected identifier" error in index.js goes away and a new error in an unrelated script occurs. So unless I am mistaken it would appear that it is running in an older rendering mode as Herst suggested.

Closing again.

**Comment by Herst** [comment]
IE5?! Were you missing a proper `DOCTYPE`?

**Comment by Soenhay** [comment]
It is a legacy website :) where I can not change the DOCTYPE. Our custom page is in an iFrame and I found that I do not really need the library on that particular site so I am no longer trying to load it there. I am using it for some older versions of Safari on iPads and iPhones and it is working great.
