### ISSUE TITLE
README Grammar Fixes

### ISSUE THREAD

**Issue by ryuhhnn** [jerrybendy/url-search-params-polyfill#22]
Used this library in one of my projects, and felt like giving back a little :) I noticed that the following sentence in the README file contains a few grammar mistakes:

> Via the data of caniuse, there are many browsers support fetch but URLSearchParams. 

I can submit a pull request so that it reads:

> Via the data of caniuse, there are many browsers that support fetch but not URLSearchParams.

Thanks for the library and happy hacking!

**Comment by jerrybendy** [comment]
PR welcome 😉   My English is not good, so it may be too many mistakes  😂  Thanks for your correction.
