### ISSUE TITLE
Throw Error "Uncaught TypeError: Cannot read property 'toString' of undefined"  in chrome of v32.xx.xx

### ISSUE THREAD

**Issue by zhayes** [jerrybendy/url-search-params-polyfill#29]
![image](https://user-images.githubusercontent.com/17758062/42617105-26e826b8-85e3-11e8-8523-ef967e3f2fb4.png)

**Comment by jerrybendy** [comment]
Issue was resolved and released a new version of `v4.0.1`

**Comment by zhayes** [comment]
@jerrybendy  thanks ! you just add  `value !== null && value !== undefined ...`

**Comment by jerrybendy** [comment]
@zhayes  Yep... I forgot that `undefined` doesn't has `toString` method, either...

**Comment by gregor** [comment]
Could you please also tag the release on GitHub?

**Comment by jerrybendy** [comment]
@gregor  Sure. And there it is.  I usually forget tagging the release 😅
