### ISSUE TITLE
URLSearchParams object cannot be iterated in a `for (const x of params)` loop

### ISSUE THREAD

**Issue by louh** [jerrybendy/url-search-params-polyfill#3]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams):

> An object implementing URLSearchParams can directly be used in a for...of structure, instead of entries(): for (var p of mySearchParams) is equivalent to for (var p of mySearchParams.entries()).

Thus, I expect this to work:

```js
  const params = new URLSearchParams(queryString); // polyfilled with url-search-params-polyfill

  for (const param of params) {
    console.log(params); // -> [key, value]
  }
```

However this will throw an error:

```
undefined is not a constructor (evaluating 'params[Symbol.iterator]()')
```

Furthermore, there is no `entries()` method so I cannot fall back to this.

**Comment by jerrybendy** [comment]
Hi,

I'm sorry about that. This library only implement the base function of URLParams now. I'll fix it as soon as possible.

Thanks for your notice.

**Comment by jerrybendy** [comment]
Hi,

I had read the MDN document twice, and I had implement all features of URLSearchParams now.

You can upgrade your `url-search-params-polyfill` dependence to version `^1.1.0` instead.

Thank you.

**Comment by louh** [comment]
Thank you so much!
