### ISSUE TITLE
Work in EDGE but doesn't work in IE11

### ISSUE THREAD

**Issue by eldyvoon** [jerrybendy/url-search-params-polyfill#30]
No error but just won't in IE11

**Comment by jerrybendy** [comment]
I just tried in IE11, and it works well. Did you do something wrong? Can you show me how you use it?

**Comment by Garionion** [comment]
When I am trying this in ie11 I got the following:
`[Vue warn]: Error in created hook: "ReferenceError: "URLSearchParams" is undefined"`
`[object Error]{description: ""URLSearchP...", message: ""URLSearchP...", name: "ReferenceEr...", number: -2146823279, stack: "ReferenceEr..."}` (expandable to the Object)

I really don't know what i am doing wrong.

I am using Vue, Typescript, Vue Bootstrap, Vuex, Vue Router.
I am using URLSearchParams like this in my main.ts

```javascript
import Vue from 'vue';
import App from './App.vue';
import router from './router';
import store from './store';
import BootstrapVue from 'bootstrap-vue';
import VueMoment from 'vue-moment';
import Datepicker from 'vuejs-datepicker';
import GridLoader from 'vue-spinner/src/GridLoader.vue';
import 'url-search-params-polyfill';

import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap-vue/dist/bootstrap-vue.css';
[…]

const app = new Vue({
	data: { loading: false },
	router,
	store,
	created() {
		setParams();
	},
	render: (h) => h(App),
}).$mount('#app');

[…]

function setParams() {
	new URLSearchParams(window.location.search);
	const urlParams = new URLSearchParams(window.location.search);
// already failed
	[…]

}

```

**Comment by jerrybendy** [comment]
@Garionion  I answered you in #36
