### ISSUE TITLE
TypeError: urlSearch[Symbol.iterator] is not a function`

### ISSUE THREAD

**Issue by julius-d** [jerrybendy/url-search-params-polyfill#31]
Hi!

I am trying to polyfill URLSearchParams so that i can use "react-query-params" (version 1.0.7) also in Firefox 24. 
But when using this polyfill I still get an error.

The error can be reproduced with that code:
```
    var urlSearch = new URLSearchParams(window.location.search); 
    var _iterator = urlSearch[Symbol.iterator]()
```
I get the error:
`TypeError: urlSearch[Symbol.iterator] is not a function`

BR

**Comment by jerrybendy** [comment]
Hi!

The latest version is `v4.0.1`. You can try to upgrade your dependency to the latest version by:

```bash
npm i -S url-search-params-polyfill@^4.0.1
```

**Comment by julius-d** [comment]
Thank you for the answer :)
