### ISSUE TITLE
Overwrite broken native support in Edge

### ISSUE THREAD

**Issue by steadicat** [jerrybendy/url-search-params-polyfill#32]
Edge has a partially-broken implementation of `URLSearchParams`. It does not properly URL-encode values in some cases. For example:

<img width="270" alt="image" src="https://user-images.githubusercontent.com/6031/44887615-f7072780-ac81-11e8-8af6-597fdf5f894b.png">

As you can see, Edge fails to escape an `&` if it's preceded by a space, which breaks the whole encoded string.

**Comment by jerrybendy** [comment]
You are right. This bug exists in Edge. Thanks for your PR 😁

**Comment by jerrybendy** [comment]
I have changed the detection to a closure to make the code looks more clearly. And released version 5.0.0 for a break change.

**Comment by erykpiast** [comment]
@jerrybendy what exactly was the breaking change?

**Comment by jerrybendy** [comment]
Ah... Alright... Maybe there is no any breaking change 😂 My mistake

**Comment by erykpiast** [comment]
:D That’s good news actually, thank you for the answer!
