### ISSUE TITLE
Please adapt semver

### ISSUE THREAD

**Issue by hackel** [jerrybendy/url-search-params-polyfill#35]
I came here because I noticed a major version upgrade from 4.0.1 to 5.0.0, indicating breaking changes, however the only thing in the release notes is "Fix ampersands encoding bug in Edge."  Is this a breaking change, and if so what are the upgrade requirements?

If not, please adopt [semver](https://semver.org/).  Specifically, this minor bug fix should have been released as version 4.0.2.  This would save anyone using your package a tremendous amount of time in determining upgrade requirements and compatibility.

Thank you!

**Comment by jerrybendy** [comment]
No break changes, I made a wrong version number 😓 https://github.com/jerrybendy/url-search-params-polyfill/issues/32
