### ISSUE TITLE
Using urlSearchParams in EDGE browser with url having special character

### ISSUE THREAD

**Issue by sajuthankathurai** [jerrybendy/url-search-params-polyfill#38]
I am using the below code to get the url params. It is working fine in Chrome but not in EDGE & IE11.  My URL has special characters in the query string for ex: http://localhost:8080/data/api?exp=$%^^%%^^*(*&

 try {
    let urlParams = new URLSearchParams(window.location.search);    
  } catch (err) {
   console.log(err)   
  }

**Comment by jerrybendy** [comment]
I think `%` is a reserved word for `decodeURIComponent`. 

![image](https://user-images.githubusercontent.com/7897384/56112832-c2d14480-5f8e-11e9-8830-0d7f94af9871.png)

**Comment by sanders54** [comment]
I'm having the same problem with Norwegian special chars converted to respective HTML entity in Edge. 

For example, "hengelås" would be "hengel%E5s" in the search param - but I get "invalid argument" when calling "new URLSearchParams(window.location.search)".

Works fine in Firefox/Chome etc.

**Comment by jerrybendy** [comment]
I'm using `decodeURIComponent` to decode a query string's value part. But when the `decodeURIComponent` meets a `%`, it will treat it as a prefix of an unicode char. As the example by @sajuthankathurai , `%^^` is not a valid encoded unicode char, so an exception thrown.

![image](https://user-images.githubusercontent.com/7897384/56675378-828c6780-66ee-11e9-8b7c-3c10551a5487.png)

Chrome's native `URLSearchParams` class handles this situation correctly. I think I can use a RegExp to find if the `%` is a valid prefix of an unicode char or not, and decode them separately.

**Comment by jerrybendy** [comment]
This issue is fixed in `v6.0.0`, you can upgrade to the latest version and retry.
