### ISSUE TITLE
ie9 do not work

### ISSUE THREAD

**Issue by smalike** [jerrybendy/url-search-params-polyfill#39]
browser : ie9
error message: params error

**Comment by jerrybendy** [comment]
你好，能提供一下具体你做了什么以及报了什么错误吗？

Hi, can you tell me what you did and what happened for detail?

**Comment by smalike** [comment]
> 你好，能提供一下具体你做了什么以及报了什么错误吗？
> 
> Hi, can you tell me what you did and what happened for detail?

```javascript
import 'url-search-params-polyfill'
const request = axios.create({
  timeout: 15000
})
  // ...
  post (url, params) {
    return {
      url,
      method: 'post',
      data: params,
      transformRequest: (data /** , headers */) => {
        return new URLSearchParams(data)
      }
    }
  }

// ...
request(this[method](url, params))
```

IE11 and IE10 work success, but IE9 message:
```
error: Error: 参数无效
```

**Comment by jerrybendy** [comment]
Ah... I can not understand what makes this error though this demo... 😞

**Comment by smalike** [comment]
> Ah... I can not understand what makes this error though this demo... 😞

at axios xhr.js 178 line
```javascript
    // Send the request
    requestData = {a: 1, b: 2}
    request.send(requestData);
```
requestData = null => request success
requestData = {xxx} => error

**Comment by jerrybendy** [comment]
I don't know anything about your `xhr.js` and I don't know how you invoke it.

I think it will be better if you could provide a full demo to illustrate what you did. It can be a jsfiddle or codepen link which I can reproduce the error by it.

**Comment by jerrybendy** [comment]
Hi, if you can't provide more information about your issue, I would close this issue now. You can create new or reopen this if you have any questions.
