### ISSUE TITLE
Chrome 50 URLSearchParams doesn't work?

### ISSUE THREAD

**Issue by mmontag** [jerrybendy/url-search-params-polyfill#4]
While testing we noticed that the URLSearchParams in Chrome 50 in Android was failing. So the polyfill wasn't working for us. Just a note for more investigation.

**Comment by jerrybendy** [comment]
Can you give me a simple demo to show me what you did? And I will try it again.

**Comment by jerrybendy** [comment]
The [can i use data](http://caniuse.com/#feat=urlsearchparams) shows that Chrome 50 support URLSearchParams originally. So the polyfill will not work. 

You can try to print `console.log(URLSearchParams.polyfill)` to ensure whether the polyfill worked. If it outputs `true`, it worked, `undefined` if it didn't.

**Comment by jerrybendy** [comment]
I'll close this issue. If any questions, please open a new issue. Thanks

**Comment by jerrybendy** [comment]
@mmontag  Did you talk about #6 issue? If so, it has fixed  🙂  Thank you

**Comment by mmontag** [comment]
Ah yes, that must have been the problem. Thanks!

**Comment by jerrybendy** [comment]
You can try to use the latest `2.0.0` version.
