### ISSUE TITLE
Constructor taking sequence-style input produces wrong output

### ISSUE THREAD

**Issue by burtyish** [jerrybendy/url-search-params-polyfill#40]
According [MDN](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams#Examples), the following usages of the constructor should be equivalent:
>// Pass in a sequence
var params3 = new URLSearchParams([["foo", 1],["bar", 2]]);

>// Pass in a record
var params4 = new URLSearchParams({"foo" : 1 , "bar" : 2});

However, given the first ('sequence') style, the constructor will produce the following:
`'0=a%2C1&1=b%2C2'` (encoded '0=a,1&1=b,2')

**Comment by jerrybendy** [comment]
Hi,

Thanks for your issue. I have fixed this and released `v7.0.0`.

**Comment by burtyish** [comment]
Thanks for the swift response!
