### ISSUE TITLE
Does not work with React Native v0.59 and up

### ISSUE THREAD

**Issue by visto9259** [jerrybendy/url-search-params-polyfill#41]
I have been using this library to use URLSearchParams in React Native without problems.

After updating React Native to version 0.59, this library no longer works because the people at FB have decided to provide a prototype for the **get()** function.  There prototype simply returns that the **get()** function is not implemented.

Since the **get()** function is tested for presence and if present, the library returns the native function, then the library becomes useless.

Here's React Native implementation of URLSearchParams
https://github.com/facebook/react-native/blob/master/Libraries/Blob/URL.js

I know that this is not necessarily an issue with this library but it is important to be aware that it cannot be used in a React Native app unless it gets fixed.

**Comment by jessep** [comment]
It would be nice to be able to just import and use this directly, rather than having to rely on the polylfill

**Comment by jerrybendy** [comment]
I don't use RN and don't know what the `get` function really is. Could you give me some more detail, or tell me how to fix it?

**Comment by visto9259** [comment]
I do not think that your library is wrong.  The issue is with React Native.  Your polyfill checks for the presence of the `get` method in the native implementation of `URLSearchParams` and uses it if it is present.  

The issue is that the implementation of `URLSearchParams` on React Native does nothing.

I created a version of your library to address my needs with React Native and made it into a class.  I do not recommend using it elsewhere than in React Native.  I have not checked the latest version of React Native so maybe this is no longer an issue.  

Check out my port of this code at [github.com/visto9259/urlsearchparams-react-native](https://github.com/visto9259/urlsearchparams-react-native)

**Comment by jerrybendy** [comment]
Maybe I got your point but I can't make sure. The codes use `(self.URLSearchParams && self.URLSearchParams.prototype.get) ? self.URLSearchParams : null` to test whether the environment supports native URLSearchParams or not. RN has a default `get` function but do nothing. This makes this polyfill treat RN has a partial support with URLSearchParams. 😓

**Comment by visto9259** [comment]
Yes,  `URLSearchParams.prototype.get` in RN exists and in fact, it throws an error.

Check out the code [here](https://github.com/facebook/react-native/blob/0.63-stable/Libraries/Blob/URL.js)

````javascript
get(name) {
    throw new Error('not implemented');
}
````

I don't understand why they have provided a limited `URLSearchParams` class.

**Comment by jerrybendy** [comment]
Maybe the way to test should change to:

```js
var isSupport = (function() {
  try {
    return (new URLSearchParams('a=1')).get('a') === '1'
  } catch() {
    return false
  } 
})()
```

**Comment by visto9259** [comment]
It would definitely be a better test.  Perhaps it would better to test against a more obscure query string like this.  Otherwise, it is a fairly good improvement that you could implement.
````javascript
var isSupport = (function() {
  try {
    return (new URLSearchParams('a=abc123')).get('a') === 'abc123'
  } catch() {
    return false
  } 
})()
````

I have not investigated why RN does not implement URLSearchParams nor why would one need a polyfill to start with in RN.  I believe there is an issue thread on this topic in the RN repo.  I will give it a look why I find some time.

In the meantime, you should update your polyfill with your suggested improvement.

**Comment by jerrybendy** [comment]
Yes, but I think there is no difference between `a=1` and `a=abc123` 😅

**Comment by visto9259** [comment]
I know.  Just being extra cautious...

**Comment by jerrybendy** [comment]
The finally code may be this:

```diff
- var nativeURLSearchParams = (self.URLSearchParams && self.URLSearchParams.prototype.get) ? self.URLSearchParams : null
+ var nativeURLSearchParams = (function() {
+   try {
+    if (self.URLSearchParams && (new self.URLSearchParams('foo=bar')).get('foo') === 'bar') {
+      return self.URLSearchParams;
+    }
+  } catch (e) {}
+    return null;
+  })()
```

**Comment by jerrybendy** [comment]
This issue has been fixed, and released as `v8.1.0`

**Comment by jerrybendy** [comment]
@jessep Good idea. I'm trying to depart `index.js` to a class file and a polyfill file, so that users can choose anyone they want.

**Comment by visto9259** [comment]
The more I read about JS classes, the more I think that this is just sugar on top of function prototyping. 
It's up to you but I would not spend time trying to convert this pacakage to a class. 
If I had to do it all over again (i.e. my port of your code to a class), I would not have done it.

**Comment by jerrybendy** [comment]
I want to keep this polyfill as simple as possible. And compatible with CMD and UMD at same time.  So I use only one file to write all codes. It's not a good idea to depart `index.js` to two files if I still want to be compatible with UMD. Could you give me some advice ?

**Comment by visto9259** [comment]
Not an expert either. Did you mean ESM and UMD?  CMD stands for CommonJS?

**Comment by jerrybendy** [comment]
Yes, ES Module. I have an idea, make the `index.js` export a class only, and use a `polyfill()` function to apply polyfill to browser, just like what the promise polyfill did. The usage colud be: 

```js
import URLSearchParams from 'url-search-params-polyfill';

// Use this class directly, instead of the native one
const params = new URLSearchParams(location.search);

// Or apply a polyfill to browser, to make it global
URLSearchParams.polyfill();
```

This would make a break change that all older versions are not compatible with this.

**Comment by visto9259** [comment]
I suggest that you take a look at how other packages are dealing with this issue.  MomentJS, for example, works in the browser, nodejs, CommonJS, RequireJS and so on.  It could be a good example to achieve compatibility.  [https://momentjs.com/docs/#/use-it](https://momentjs.com/docs/#/use-it)
What I have seen, if you want to make the polyfill to be applied to the browser, is that extra steps are required as you suggest.  The extra step can be automated in loaders like RequireJS and bundlers like Webpack.
Not sure if this is helping you.

**Comment by pjc0247** [comment]
`[TypeError: Object is not a constructor (evaluating 'new _urlSearchParamsPolyfill.default(path.split('?', 2)[1])')]`

i got this error with `"url-search-params-polyfill": "^8.1.1"`
