### ISSUE TITLE
Sporadic error on Edge

### ISSUE THREAD

**Issue by samsondav** [jerrybendy/url-search-params-polyfill#42]
We are occasionally seeing this error:

```
TypeError Cannot set property URLSearchParams of [object Object] which has only a getter 
    https://polyfill.io/v3/polyfill.min.js:3:11759 
    https://polyfill.io/v3/polyfill.min.js:3:11762 
    https://polyfill.io/v3/polyfill.min.js:3:12205 
    https://polyfill.io/v3/polyfill.min.js:3:12215 
```

It has been observed on the following browser versions:

```
browserName

Edge

browserVersion

18.17763.0

locale

en-GB

osName

Windows 10.0

time

2019-09-18T21:30:54.670Z

userAgent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763
```

And also

```
browserName

Edge

browserVersion

16.16299.0

locale

en-US

osName

Windows 10.0

time

2019-09-18T17:19:16.278Z

userAgent

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299
```

Unfortunately we haven't been able to reliably reproduce it.

**Comment by jerrybendy** [comment]
I don't know what your problem really is. I opened `https://polyfill.io/v3/polyfill.js` in Edge, and read the code. The implementation of `URLSearchParams` in `polyfill.io` is not from my library. I'm not able to help you because  I'm not familiar with these codes.

**Comment by akomm** [comment]
@samphilipd can you siwitch to the dev version instead of min and tell the version of library and the line where the error is thrown.
