### ISSUE TITLE
Hey, what's the reason for this

### ISSUE THREAD

**Issue by bosens-China** [jerrybendy/url-search-params-polyfill#46]
``` js
    function encode(str) {
        var replace = {
            '!': '%21',
            "'": '%27',
            '(': '%28',
            ')': '%29',
            '~': '%7E',
            '%20': '+',
            '%00': '\x00'
        };
        return encodeURIComponent(str).replace(/[!'\(\)~]|%20|%00/g, function(match) {
            return replace[match];
        });
    }
``` 
Why not use encodeuri?
Instead, the above specific characters are processed separately

**Comment by jerrybendy** [comment]
`encodeURI` is different from `encodeURIComponent`, you can get so many articles to know their difference with easy. And both of them can not handle chars listed in the `replace` object.

**Comment by bosens-China** [comment]
Yes, they are different, but why do the characters listed above need to be processed separately

**Comment by jerrybendy** [comment]
Refer to [MDN encodeURIComponent document](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent), some chars listed would not be escaped by `encodeURIComponent`, but they are not standard chars in RFC documents either. You can see the [examples](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent#Examples) or read RFC3986 & RFC5987 to get more details.

**Comment by bosens-China** [comment]
Thank you the problem has been solved, symbol escape for safety and integrity
