### ISSUE TITLE
improperly encodes values in toString()

### ISSUE THREAD

**Issue by robbiemu** [jerrybendy/url-search-params-polyfill#48]
we use this to simulate a form post. In chrome, where the polyfill is not loaded, I can pass a url as a parameter:

```
params.set('target', '/url/as/a/parameter');
```
in the network tab, I see in the request body:
```
target: /url/as/a/parameter
```

but in IE 11, which needs the polyfill, I see:
```
target: %2Furl%2Fas%2Fa%2Fparameter
```

**Comment by jerrybendy** [comment]
Hi,

I tested your case in both chrome and IE, it worked well.

```js
var a = new URLSearchParams()
a.set('t', '/url/a/b')
a.get('t')  // returns /url/a/b
a.toString()  // returns t=%2Furl%2Fa%2Fb
```

The results in Chrome 83 (without polyfill) and IE 11 (with polyfill) are same.

You mentioned that it's in the Network tab. I think this is a feature of Chrome that request parameters are defaultly decoded for good reading. You can click *view source* to get the original string in Network tab.

**Comment by robbiemu** [comment]
I'm sorry .. In fact, I came to post this here because the only other option would seem to be a problem in angular 5. I am consuming the code like this:

```typescript
  private getUrlSearchParams(payload: any) {
    const params = new URLSearchParams();
    Object.keys(payload)
      .forEach(key => {
        const value = payload[key];
        params.set(key, String(value));
      });
    return params.toString();
  }
// ...
       const payload: SignInPayload = { USER: this.username, PASSWORD: this.password};
    if (this.localService.Target) {
      payload.Target = this.localService.Target;
    }
//...
    const body = this.getUrlSearchParams(payload);

    const headers = {
      'Accept': 'text/html',
      'Content-Type': 'application/x-www-form-urlencoded'
    };

    const handleLoginFailure = (err) => { /**/ };

    return this.nakedHttpClient.post(
      authenticationRedirectUrl,
      body,
      {
        observe: 'response',
        responseType: 'text',
        headers
      }
    )
```

in chrome the network tab shows a body with `Target: /url/to/redirect-after-login`
but only in ie11 instead I see this in the request body: 'Target: %2Furl%2Fto%2Fredirect-after-login'

**Comment by jerrybendy** [comment]
I can't make sure whether it is any difference between Chrome and IE11 in the Network panel. I think the most correct way to judge the difference is using a backend server, and get the `Target` value from the backend. If PHP, you can use

```php
echo $_POST['Target'];
```

If the values are same, it means there is no difference.

By the way, the `getUrlSearchParams` is not needed. You can use `const body = new URLSearchParams(payload)` directly.
