### ISSUE TITLE
toString method doesn't encode equal (=) right in Safari 10

### ISSUE THREAD

**Issue by kasperpeulen** [jerrybendy/url-search-params-polyfill#49]
We switched from https://github.com/ungap/url-search-params to this polyfill, but we found problems in some browsers related to that switch.

The toString method doesn't work well, in some browsers, we see GET request logged like this:
`checkout?order-candidate-id%2Cabc` 
where it should be
`checkout?order-candidate-id=abc` 

Top 5 User agents where this happens:
* Safari 10 on iOS 10.3 | Mozilla/5.0 (iPad; CPU OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1
* Safari 10 on iOS 10.3 | Mozilla/5.0 (iPad; CPU OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1
* Safari 10.1 on Mac OS X (Yosemite) | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8
* Safari 10 on iOS 10.3 | Mozilla/5.0 (iPad; CPU OS 10_3_4 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G61 Safari/602.1
* Webkit based browser on iOS 10.3 | Mozilla/5.0 (iPad; CPU OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Mobile/14G60

**Comment by jerrybendy** [comment]
Hi,

Could you show me how you use this class? I have tried like below, it worked well. `=` is a special char in a query string, and it could not be escapled.

```js
var a = new URLSearchParams({'order-candidate-id': 'abc'})
console.log(a.toString())

var b = new URLSearchParams('order-candidate-id=abc')
console.log(b.toString())
```
