### ISSUE TITLE
sort()

### ISSUE THREAD

**Issue by stevenvachon** [jerrybendy/url-search-params-polyfill#5]
is missing

**Comment by jerrybendy** [comment]
Hi,
`URLSearchParams` has no `sort` method.  https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

**Comment by stevenvachon** [comment]
https://url.spec.whatwg.org/#urlsearchparams

**Comment by jerrybendy** [comment]
Oh my! They are different !! 😱

**Comment by stevenvachon** [comment]
MDN is way outdated. WHATWG is the source.

**Comment by jerrybendy** [comment]
Ok, I'll read that and fix it soon. Thanks

**Comment by jerrybendy** [comment]
It's fixed. Please upgrade to `v1.2.0`. Thanks
