### ISSUE TITLE
Support for size prop

### ISSUE THREAD

**Issue by AndyOGo** [jerrybendy/url-search-params-polyfill#51]
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/size

**Comment by jerrybendy** [comment]
Thanks for your issue. `size` support is now added on `v8.2.0`.

**Comment by lukezavrel** [comment]
This probably broke something, with 8.2.0, I am getting this error
<img width="623" alt="image" src="https://github.com/jerrybendy/url-search-params-polyfill/assets/36727740/f68bea9d-43c4-41f0-a069-6fc9dc492ffc">
<img width="817" alt="image" src="https://github.com/jerrybendy/url-search-params-polyfill/assets/36727740/4ef0959d-5b94-471a-b2f6-08162edbc934">

**Comment by xolott** [comment]
Same issue here. We rolled back to 8.1.1

**Comment by jerrybendy** [comment]
Sorry about that....

Maybe we can use `URLSearchParams.prototype.hasOwnProperty('size')` instead of `URLSearchParams.prototype.size`

**Comment by guidodinatale** [comment]
@jerrybendy I think this is not the root of the issue. I tried making this change but I still get the following on Safari when inspecting `URLSearchParams.prototype`:
<img width="708" alt="image" src="https://github.com/jerrybendy/url-search-params-polyfill/assets/87653434/4101c50a-6f9d-4003-8923-2a76e968e29c">

I think it is an issue with the scoping of `this` inside the `defineProperty` getter.

**Comment by jerrybendy** [comment]
@guidodinatale  I only tested this in nodejs. This is my fault, and I'm handling on this

**Comment by jerrybendy** [comment]
`v8.2.2` fixes this issue. If you got any problem about this, please let me know. Thanks
