### ISSUE TITLE
Major issue with this library breaking on Safari

### ISSUE THREAD

**Issue by badddams** [jerrybendy/url-search-params-polyfill#54]
Hi there,

We recently upgraded to the newer version **8.2.3** but since upgrading, all POST requests using URL Search Params seem to be sending the data across in JSON as opposed to Form Data like they were previously. Because of this, it causes the browser to break in Safari and post an error.

I was only able to catch this by going through each of my dependencies and finding the root cause.

Thanks in advance but will hardcode our version to **8.1.1** for now as this seems to keep things working.

**Comment by jerrybendy** [comment]
I tried on Safari 15.6.1, and it works well. Could you make a demo to show this issue ?

```js
var a = new URLSearchParams({a: 1, b: 2})
fetch('/', {body: a, method: 'POST'})
```

![image](https://github.com/jerrybendy/url-search-params-polyfill/assets/7897384/f75f80d4-fb01-41c3-82d2-e110c2005c92)

**Comment by badddams** [comment]
Hey @jerrybendy thanks for getting back to me, I'm using it in this context.

```js
var params = new URLSearchParams();

params.append('inputname', 'jerry');

axios.post(url, params, config);
```

I appreciate that I'm not using fetch like in your example above but prior to this update, it all worked perfectly.

**Comment by jerrybendy** [comment]
I got your problem and fixed it. You can try `v8.2.4`.

Axios using `toString.call` to check an object is `URLSearchParams` or not. So when `Proxy` is not used, `toString.call` reteruns an incorrect value. This triggers this issue.

Another mistake is checking `useProxy` conditions returns an incorrect value. Safari 15 should use `Proxy`, but the code returns `false`.

**Comment by badddams** [comment]
Amazing, great work @jerrybendy thanks for resolving so quickly!
