### ISSUE TITLE
Does not work with IOS mobile device.

### ISSUE THREAD

**Issue by nikhillale** [jerrybendy/url-search-params-polyfill#55]
I have been using this library to use URLSearchParams in AEM project without problems.

When we are using it on mobile device getting **TypeError**  with .sort() method , even those we are not using sort method anywhere in our project.

Check out the code at line no. 184.

**Comment by jerrybendy** [comment]
Could you tell more details about this error?

**Comment by nikhillale** [comment]
[
<img width="703" alt="Screenshot 2023-09-01 at 2 55 31 PM" src="https://github.com/jerrybendy/url-search-params-polyfill/assets/52103074/daf071ef-a60e-4040-bb77-5326261b0c78">

**Comment by jerrybendy** [comment]
I cannot repeat your issue, which browser and version do you use?

**Comment by nikhillale** [comment]
On iOS mobile device (iPhone 13, iOS version - 16)  and Safari browser version - 16

**Comment by jerrybendy** [comment]
My phone is also iPhone 13 and iOS 16, and I tested this code on Safari 16.6, this issue is not been repeated. I'll try to change line 184 like below. If you have time, you can help test if it works.

```diff
- USPProto.sort = USPProto.sort || function() {
+ if (sort in USPPproto) {
```
