### ISSUE TITLE
Bad feature detection on chrome

### ISSUE THREAD

**Issue by SleepWalker** [jerrybendy/url-search-params-polyfill#6]
Hello,

according to https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams, only firefox has full `URLSearchParams` support. The other browsers have only a basic support or no support at. With the second group everything is ok, but with the first group, even after appling this polyfill, the following test will fail:

```js
new URLSearchParams({foo: 'bar'}) == 'foo=bar'
```

I sugest to replace in `index.js`:

```js
if (self.URLSearchParams) {
    return;
}
```

with

```js
try {
    if (self.URLSearchParams && new (self.URLSearchParams)({foo: 'bar'}) == 'foo=bar') {
        return;
    }
} catch (err) {
    // we'd better polyfill this case too
}
```

@jerrybendy if you are agree, I can create a pull request.

**Comment by SleepWalker** [comment]
btw. #4 addresses the same problem

**Comment by jerrybendy** [comment]
Hi,

Thanks for your suggest. I had got the same problem when I use URLSearchParams on chrome too. 

Your example code can resolve this issue well. Although I don't know if any more graceful way to handle it with. Totally, I accept your code.  😜

Thank you

**Comment by SleepWalker** [comment]
Hi, thank you very much.

I'm too busy this weeks, so I haven't found the time to make a pull request
personally

**Comment by jerrybendy** [comment]
Hi, `v1.3.0` has released with this feature.
