### ISSUE TITLE
Since 1.3.0 URLSearchParams results in empty post data when used for body on a google chrome native fetch() api call

### ISSUE THREAD

**Issue by etremblay** [jerrybendy/url-search-params-polyfill#8]
Js code snippet to reproduce:
```
let body = new URLSearchParams("&b=555");
console.log(body.toString());
fetch('/test.php',   { method : 'POST', body })
  .then(response => response.json())
  .then(console.log);
```

test.php
```
<?php
echo json_encode($_POST);
```

Result with native chrome URLSearchParams (1.2.0) : 
```
"b=555"
Object {b: "555"}
```

With polyfilled URLSearchParams (1.3.0):
```
"b=555"
[]
```

Tested on google chrome 59 linux

**Comment by jerrybendy** [comment]
Hi,

The difference between v1.2.0 and v1.3.0 is that v1.3.0 added an examination to check if browser version has full support for `URLSearchParams` (It checks if browser has support for construct URLSearchParams object with an object). In fact, Chrome 59 doesn't support construct with an object, so the polyfill worked.

When use native `fetch`, the URLSearchParams-polyfill is not the same to the native implementation, so it's different.

I researched Chrome's `fetch` and `URLSearchParams` 's source code which are written by `cpp`. The source is here ([URLSearchParams](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/dom/URLSearchParams.cpp) / [fetch](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/fetch/Body.cpp?l=91)).  I'm sorry I can't read it very clearly. 

The [spec](https://fetch.spec.whatwg.org/#body-mixin) shows when use an `URLSearchParams` object as `body` content, `fetch` will set a `Content-Type` to `application/x-www-form-urlencoded;charset=UTF-8` automatically.

I don't have good solution to handle this issue. If you want to use the constructor such as `new URLSearchParams({key: 'hello world'})`, v1.3.0 is it. But if you want to use the polyfill with `fetch`, you should do something else, like:

```js
const body = new URLSearchParams({
  keyworld: 'hello world'
});
const headers = new Header();
headers.set('Content-Type', 'application/x-www-form-urlencoded;charset=UTF-8');

fetch('https://httpbin.org/post', {
  method: 'post',
  body,
  headers,
}).then(.....)
```

**Comment by etremblay** [comment]
Hi,

Thanks for the quick and elaborate response.

Your solution make sense, we already did the Content-Type trick on cases where we used string body.

Unfortunately, even with the Content-Type header, chrome still send empty post data for fetch requests.

I guess I will have to stick to 1.2 or always convert URLSearchParams to string before doing fetch.

**Comment by etremblay** [comment]
I just taught of a way you could handle object arguments without losing the native advantages of the component.

You could wrap the "constructor" to create a native URLSearchParam instance, parse the arguments and then use `set()` on the native instance to populate it.

**Comment by jerrybendy** [comment]
It sounds a very good idea 👍. I'll have a try and reply you the result 😀 Thanks

**Comment by jerrybendy** [comment]
Hi,

I'm sorry for answer you too late. 

Now I use a `Proxy` warper for this situation. I looked up the support of [Proxy](http://caniuse.com/#feat=proxy), and it shows that browsers which support [URLSearchParams](http://caniuse.com/#feat=urlsearchparams) are all support Proxy too.

The PR #9 fixed this issue with `Proxy` feature. Can you have a try and give me some advice?

Thank you

**Comment by jerrybendy** [comment]
Hi, the `v2.0.0` has released. You can upgrade to the latest version. Thanks.

**Comment by etremblay** [comment]
Hi, 

Great news.  it's pretty busy up here, sorry for not being able to try it.
